---
title: "Results from CEV surveys"
subtitle: "On mental health, underlying conditions, access to services and employment"
author: "Sebastien Peytrignet, The Health Foundation"
date: "4/1/2021"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    toc: TRUE
---

```{r setup.A, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,stringr,ggplot2,easycsv,
               gmodels,Rmisc,DescTools,data.table,
               tibble,plotly,lubridate,
               here,RColorBrewer,ggthemes,hrbrthemes,
               tidyverse,showtext,
               knitr,kableExtra)

#Clean up the global environment
rm(list = ls())

#Set directory where inputs are saved
rawdatadir <- "M:/Analytics/Networked Data Lab/Shielding/Shielding Behavioural Survey/"

#Git directory
gitdir <- dirname(rstudioapi::getSourceEditorContext()$path)

#Set directory
setwd(rawdatadir)

##################################################
################### Load clean data ##############
##################################################

fread_folder(paste0(gitdir,"/Clean data/"), extension = "CSV")

```

## Changes in mental health and well-being

### COVID High Risk Group Insights Survey (2021)

```{r mh1_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6}

COVID_HRGS_MH1_data <- CHRGIS_mh1_clean %>%
  filter(.,level != "Don't know") %>%
  mutate(.,date=lubridate::dmy(date)) %>%
  mutate(., level = factor(level, levels=c("Much worse", "Slightly worse",
                                           "No difference", 
                                           "Slightly better", "Much better"))) %>%
  select(.,-c("Total"))

COVID_HRGS_MH1 <- COVID_HRGS_MH1_data %>%
  ggplot(., aes(fill=level, y=pct_clean, x=date)) + 
  geom_bar(position="stack", stat="identity") +
  theme_ipsum() +
  guides(fill=guide_legend(title="Change")) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_MH1_data$date)) +
  labs(title="Change in well-being and mental health compared to last month",
       x ="Survey date", y = "% of CEV people") +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.ticks.x=element_blank(),
        legend.text=element_text(size=11),
        text = element_text(size = 11),
        axis.text = element_text(size =11),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(size =11),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")))

ggplotly(COVID_HRGS_MH1) %>%
  layout(title = list(text = paste0('Change in well-being and mental health compared to last month',
                                    '<br>',
                                    '<sup>',
                                    'COVID High Risk Group Insights Survey (2021)',
                                    '</sup>')))

COVID_HRGS_MH1_data %>%
  kable(.,digits=1,format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10)

```

### Shielding Behavioural Survey (2020)

```{r mh1_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6}

SBS_MH1_data <- SBS_mh1_clean %>%
  filter(.,!(level %in% c("Total"))) %>%
  mutate(.,date=lubridate::dmy(date)) %>%
  mutate(., level = factor(level, levels=c("Much worse", "Slightly worse",
                                           "No difference", 
                                           "It's better"))) %>%
  select(.,-c("Total"))

SBS_MH1 <- SBS_MH1_data %>%
  ggplot(., aes(fill=level, y=pct_clean, x=date)) + 
  geom_bar(position="stack", stat="identity") +
  theme_ipsum() +
  guides(fill=guide_legend(title="Change")) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_MH1_data$date)) +
  labs(title="Change in well-being and mental health since shielding guidance",
       x ="Survey date", y = "% of CEV people") +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.ticks.x=element_blank(),
        legend.text=element_text(size=11),
        text = element_text(size = 11),
        axis.text = element_text(size =11),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(size =11),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")))

ggplotly(SBS_MH1) %>%
  layout(title = list(text = paste0('Change in well-being and mental health since shielding guidance',
                                    '<br>',
                                    '<sup>',
                                    'Shielding Behavioural Survey (2020)',
                                    '</sup>')))

SBS_MH1_data %>%
  kable(.,digits=1,format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10)

```

## Treatment for mental health

### COVID High Risk Group Insights Survey (2021)

```{r mh2_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=8}

COVID_HRGS_MH2_data <- CHRGIS_mh2_clean %>%
  filter(.,!(level %in% c("Don't know","Prefer not to say"))) %>%
  mutate(.,date=lubridate::dmy(date)) %>%
  mutate(., level = factor(level, levels=c("I'm currently receiving treatment and I have also received treatment in the past",
                                           "I'm currently receiving treatment for the first time",
                                           "I have received treatment in the past, but do not receive treatment now", 
                                           "I have never received treatment")))

COVID_HRGS_MH2 <- COVID_HRGS_MH2_data %>%
  ggplot(., aes(fill=level, y=pct_clean, x=date)) + 
  geom_bar(position="stack", stat="identity") +
  theme_ipsum() +
  guides(fill=guide_legend(title="Treatment")) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_MH2_data$date)) +
  labs(title="Treatment for mental health difficulties",
       x ="Survey date", y = "% of CEV people") +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.ticks.x=element_blank(),
        legend.text=element_text(size=8),
        text = element_text(size = 11),
        axis.text = element_text(size =11),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(size =11),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")))

ggplotly(COVID_HRGS_MH2) %>%
  layout(title = list(text = paste0('Treatment for mental health difficulties',
                                    '<br>',
                                    '<sup>',
                                    'COVID High Risk Group Insights Survey (2021)',
                                    '</sup>')))

COVID_HRGS_MH2_data %>%
  kable(.,digits=1,format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10)

```

### Shielding Behavioural Survey (2020)

```{r mh2_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=8}

SBS_MH2_data <- SBS_mh2_clean %>%
  filter(.,!(level %in% c("Total","I prefer not to answer this question"))) %>%
  mutate(.,date=lubridate::dmy(date)) %>%
  mutate(., level = factor(level, levels=c("I'm currently receiving treatment for mental health problems",
                                           "I have received treatment for mental health problems in the past",
                                           "I have never received treatment for mental health problems")))

SBS_MH2 <- SBS_MH2_data %>%
  ggplot(., aes(fill=level, y=pct_clean, x=date)) + 
  geom_bar(position="stack", stat="identity") +
  theme_ipsum() +
  guides(fill=guide_legend(title="Change")) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_MH2_data$date)) +
  labs(title="Treatment for mental health difficulties",
       x ="Survey date", y = "% of CEV people") +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.ticks.x=element_blank(),
        legend.text=element_text(size=8),
        text = element_text(size = 11),
        axis.text = element_text(size =11),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(size =11),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")))

ggplotly(SBS_MH2) %>%
  layout(title = list(text = paste0('Treatment for mental health difficulties',
                                    '<br>',
                                    '<sup>',
                                    'Shielding Behavioural Survey (2020)',
                                    '</sup>')))

SBS_MH2_data %>%
  kable(.,digits=1,format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10)

```

<!-- ## Life satisfaction -->

<!-- Life satisfaction has remained stable among CEV people in both surveys. There is a drop between the 2020 and 2021 surveys, although this may reflect differences in the survey design or composition of the cohort. Older adults tend to have relatively high levels of life satisfaction compared to other age groups. -->

<!-- ### COVID High Risk Group Insights Survey (2021) -->

<!-- ```{r mh3_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=7,fig.height=5} -->

<!-- COVID_HRGS_MH3_data <- CHRGIS_mh3_clean %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) -->

<!-- pd <- position_dodge(0.1) # move them .05 to the left and right -->

<!-- COVID_HRGS_MH3 <- COVID_HRGS_MH3_data %>% -->
<!--   ggplot(., aes(x=date, y=Mean)) + -->
<!--   scale_y_continuous(limits = c(0, 10)) + -->
<!--   geom_errorbar(aes(ymin=LCL, ymax=UCL), colour="black", width=.1, position=pd) + -->
<!--   geom_line(position=pd) + -->
<!--   geom_point(position=pd, size=3, shape=21, fill="white") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_MH3_data$date)) + -->
<!--   labs(title="Life satisfaction", -->
<!--        x ="Survey date", y = "Mean (with CI)") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(COVID_HRGS_MH3) %>% -->
<!--   layout(title = list(text = paste0('Mean life satisfaction', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'COVID High Risk Group Insights Survey (2021)', -->
<!--                                     '</sup>'))) -->

<!-- COVID_HRGS_MH3_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ### Shielding Behavioural Survey (2020) -->

<!-- ```{r mh3_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=7,fig.height=5} -->

<!-- SBS_MH3_data <- SBS_mh3_clean %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) -->

<!-- pd <- position_dodge(0.1) # move them .05 to the left and right -->

<!-- SBS_HRGS_MH3 <- SBS_MH3_data %>% -->
<!--   ggplot(., aes(x=date, y=Mean)) + -->
<!--   scale_y_continuous(limits = c(0, 10)) + -->
<!--   geom_line(position=pd) + -->
<!--   geom_point(position=pd, size=3, shape=21, fill="white") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_MH3_data$date)) + -->
<!--   labs(title="Life satisfaction", -->
<!--        x ="Survey date", y = "Mean") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(SBS_HRGS_MH3) %>% -->
<!--   layout(title = list(text = paste0('Mean life satisfaction', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'Shielding Behavioural Survey (2020)', -->
<!--                                     '</sup>'))) -->

<!-- SBS_MH3_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ## Access to GP/hospital care -->

<!-- For the majority of CEV people, the amount of GP/hospital care has continued "as normal" in early 2021 and also between May-July 2020 (the biggest disruptions would have occurred at the beginning of the March 2020 lockdown and during the November-December 2020 lockdowns). In May-July 2020, about 30% of CEV people were reporting problems with access to care since being asked to shield. However, comparing results between both surveys is difficult because of the shifting reference points. -->

<!-- ### COVID High Risk Group Insights Survey (2021) -->

<!-- ```{r ac1_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6} -->

<!-- COVID_HRGS_AC1_data <- CHRGIS_ac1_clean %>% -->
<!--   filter(.,!(level %in% c("Don't know4"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   mutate(., level = factor(level, levels=c("Stopped", -->
<!--                                            "Decreased", -->
<!--                                            "Continued as normal",  -->
<!--                                            "Increased"))) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- COVID_HRGS_AC1 <- COVID_HRGS_AC1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "BrBG") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_AC1_data$date)) + -->
<!--   labs(title="Amount of GP/hospital care for underlying condition(s) since last month", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(COVID_HRGS_AC1) %>% -->
<!--   layout(title = list(text = paste0('Amount of GP/hospital care for underlying condition(s) since last month', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'COVID High Risk Group Insights Survey (2021)', -->
<!--                                     '</sup>'))) -->

<!-- COVID_HRGS_AC1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ### Shielding Behavioural Survey (2020) -->

<!-- ```{r ac1_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=9,fig.height=7} -->

<!-- SBS_AC1_data <- SBS_ac1_clean %>% -->
<!--   mutate(.,level=str_replace_all(level,"’","'")) %>% -->
<!--   mutate(.,level=str_replace_all(level,"eg","e.g.")) %>% -->
<!--   filter(.,!(level %in% c("Total"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   mutate(., level = factor(level, levels=c("I'm not accessing any care", -->
<!--                                            "I'm no longer accessing some aspects of my care, e.g. tests, scans", -->
<!--                                            "My care has continued as normal", -->
<!--                                            "My care has increased"))) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- SBS_AC1 <- SBS_AC1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "BrBG") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_AC1_data$date)) + -->
<!--   labs(title="Amount of GP/hospital care for underlying condition(s) since shielding guidance", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(SBS_AC1) %>% -->
<!--   layout(title = list(text = paste0('Amount of GP/hospital care for underlying condition(s) since shielding guidance', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'Shielding Behavioural Survey (2020)', -->
<!--                                     '</sup>'))) -->
<!-- SBS_AC1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ## Change in underlying condition -->

<!-- During May-July 2020, most CEV people reported that their condition was about the same since being asked to shield. For about 1 in 5, however, it was getting worse. Between December 2020 and January 2021, most CEV people's underlying conditions didn't change. -->

<!-- ### COVID High Risk Group Insights Survey (2021) -->

<!-- ```{r ch1_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6} -->

<!-- #Part 1 -->

<!-- COVID_HRGS_CH1_data <- CHRGIS_ch1_clean %>% -->
<!--   filter(.,!(level %in% c("Prefer not to say"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   mutate(., level = factor(level, levels=c("Yes", -->
<!--                                            "No"))) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- COVID_HRGS_CH1 <- COVID_HRGS_CH1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "Set1") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_CH1_data$date)) + -->
<!--   labs(title="Change in underlying condition since early Dec 2020", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(COVID_HRGS_CH1) %>% -->
<!--   layout(title = list(text = paste0('Change in underlying condition since early Dec 2020', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'COVID High Risk Group Insights Survey (2021)', -->
<!--                                     '</sup>'))) -->

<!-- COVID_HRGS_CH1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->


<!-- #Part 2 -->

<!-- COVID_HRGS_CH2_data <- CHRGIS_ch2_clean %>% -->
<!--   filter(.,!(level %in% c("Prefer not to say","Don't know"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   mutate(., level = factor(level, levels=c("Much worse now", -->
<!--                                            "Slightly worse now", -->
<!--                                            "Slightly better now", -->
<!--                                            "Much better now"))) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- COVID_HRGS_CH2 <- COVID_HRGS_CH2_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "RdYlGn") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_CH2_data$date)) + -->
<!--   labs(title="Change in underlying condition since early Dec 2020 (among those with change)", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(COVID_HRGS_CH2) %>% -->
<!--   layout(title = list(text = paste0('Change in underlying condition since early Dec 2020 (among those with change)', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'COVID High Risk Group Insights Survey (2021)', -->
<!--                                     '</sup>'))) -->

<!-- COVID_HRGS_CH2_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ### Shielding Behavioural Survey (2020) -->

<!-- ```{r ch1_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6} -->

<!-- SBS_AC1_data <- SBS_ch1_clean %>% -->
<!--   filter(.,!(level %in% c("Total"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   mutate(., level = factor(level, levels=c("Condition is much worse", -->
<!--                                            "Condition is slightly worse", -->
<!--                                            "Condition is about the same", -->
<!--                                            "Condition is slightly better", -->
<!--                                            "Condition is better"))) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- SBS_AC1 <- SBS_AC1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "RdYlGn") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_AC1_data$date)) + -->
<!--   labs(title="Change in underlying condition since since shielding guidance", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(SBS_AC1) %>% -->
<!--   layout(title = list(text = paste0('Change in underlying condition since shielding guidance', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'Shielding Behavioural Survey (2020)', -->
<!--                                     '</sup>'))) -->
<!-- SBS_AC1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ## Employment status -->

<!-- Over half of CEV people are retired, reflecting their age composition. -->

<!-- ### COVID High Risk Group Insights Survey (2021) -->

<!-- ```{r w1_2021, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6} -->

<!-- COVID_HRGS_W1_data <- CHRGIS_w1_clean %>% -->
<!--   filter(.,!(level %in% c("Don't know4"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- COVID_HRGS_W1 <- COVID_HRGS_W1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Situation")) + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(COVID_HRGS_W1_data$date)) + -->
<!--   labs(title="Current work situation", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(COVID_HRGS_W1) %>% -->
<!--   layout(title = list(text = paste0('Current work situation', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'COVID High Risk Group Insights Survey (2021)', -->
<!--                                     '</sup>'))) -->

<!-- COVID_HRGS_W1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->

<!-- ### Shielding Behavioural Survey (2020) -->

<!-- ```{r w1_2020, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=6} -->

<!-- SBS_W1_data <- SBS_w1_clean %>% -->
<!--   filter(.,!(level %in% c("Total"))) %>% -->
<!--   mutate(.,date=lubridate::dmy(date)) %>% -->
<!--   select(.,-c("Percentage")) -->

<!-- SBS_W1 <- SBS_W1_data %>% -->
<!--   ggplot(., aes(fill=level, y=pct_clean, x=date)) +  -->
<!--   geom_bar(position="stack", stat="identity") + -->
<!--   theme_ipsum() + -->
<!--   guides(fill=guide_legend(title="Change")) + -->
<!--   scale_fill_brewer(palette = "Set2") + -->
<!--   scale_x_date(date_labels = "%b %d %Y", breaks = unique(SBS_W1_data$date)) + -->
<!--   labs(title="Normally work or not", -->
<!--        x ="Survey date", y = "% of CEV people") + -->
<!--   theme(panel.border = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), -->
<!--         axis.ticks.x=element_blank(), -->
<!--         legend.text=element_text(size=11), -->
<!--         text = element_text(size = 11), -->
<!--         axis.text = element_text(size =11), -->
<!--         axis.text.x = element_text(angle = 45, hjust = 1), -->
<!--         axis.title.y = element_text(size =11), -->
<!--         axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"))) -->

<!-- ggplotly(SBS_W1) %>% -->
<!--   layout(title = list(text = paste0('Normally work or not', -->
<!--                                     '<br>', -->
<!--                                     '<sup>', -->
<!--                                     'Shielding Behavioural Survey (2020)', -->
<!--                                     '</sup>'))) -->
<!-- SBS_W1_data %>% -->
<!--   kable(.,digits=1,format.args = list(big.mark = ",")) %>% -->
<!--   kableExtra::kable_styling(.,bootstrap_options = c("striped", "hover"),full_width = F, font_size= 10) -->

<!-- ``` -->
